# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hersko < Formula
  desc "CLI for the Hersko workout-tracking server"
  homepage "https://hersko.app"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hersko.app/v0.1.0/hersko_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f84dd79e450cea38a1bb5a9e5f07e328ef052a81511351520c8c542cd813dac3"

      define_method(:install) do
        bin.install "hersko"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hersko.app/v0.1.0/hersko_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7a615cbb91930f39353ba08e21f6dfde0aa7fde85620afe41af479971ddf1e4a"

      define_method(:install) do
        bin.install "hersko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.hersko.app/v0.1.0/hersko_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c036337d87825787df33b3002ddb4cd531724e459af15ea0b542263a4747bde0"
      define_method(:install) do
        bin.install "hersko"
      end
    end
  end

  test do
    assert_match "hersko", shell_output("#{bin}/hersko version")
  end
end
