# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hersko < Formula
  desc "CLI for the Hersko workout-tracking server"
  homepage "https://hersko.app"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hersko.app/v0.1.1/hersko_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b3902d55027cca7114bcd68f205729fdceeeab039aecbfc303286f57a34601e7"

      define_method(:install) do
        bin.install "hersko"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hersko.app/v0.1.1/hersko_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "803088a173bc8d3f833133f6a5c258302b50084a7dedd973a2643c008eef46ac"

      define_method(:install) do
        bin.install "hersko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.hersko.app/v0.1.1/hersko_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b1fb3146a3fc756fcddca0eea359a7020bdcecb0ebff925c69d2ce1766e6497d"
      define_method(:install) do
        bin.install "hersko"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hersko version")
  end
end
